Handle exception when scrolling.
We got the following exception, which doesn't have a single
hit on Google!

```
BrowserManager       - INFO     - BROWSER 38: Crash in driver, restarting browser manager
 Traceback (most recent call last):
  ...
  File "/home/gacar/dev/OpenWPM_Leuven_Princeton/automation/Commands/utils/form_utils.py", line 210, in fill_input_elements_and_submit
    wd_ext.scroll_to_bottom(driver)
  File "/home/gacar/dev/OpenWPM_Leuven_Princeton/automation/Commands/utils/webdriver_extensions.py", line 27, in scroll_to_bottom
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: o.offset is not a function
Stacktrace:
```